export const API = {
	AUTH: {
		REGISTER: "/auth/register",
		LOGIN: "/auth/login",
		REFRESH: "/auth/refresh",
		LOGOUT: "/auth/logout",
		ME: "/auth/me",
	},
	ITEMS: {
		LIST: "/masters/items",
		CREATE: "/masters/items",
		GET_ONE: (id: string) => `/masters/items/${id}`,
		UPDATE: (id: string) => `/masters/items/${id}`,
	},
	ORDERS: {
		LIST: "/orders/order-list",
		CREATE: "/orders/order-list",
		GET_ONE: (id: string) => `/orders/order-list/${id}`,
		UPDATE: (id: string) => `/orders/order-list/${id}`,
		UPDATE_STATUS: (id: string) => `/orders/order-list/${id}/status`,
		CREATE_FROM_QUOTATION: (quotationId: string) =>
			`/orders/order-list/from-quotation/${quotationId}`,
	},
	USERS: {
		LIST: "/users",
		CREATE: "/users",
		GET_ONE: (id: string) => `/users/${id}`,
		UPDATE: (id: string) => `/users/${id}`,
		UPDATE_PASSWORD: (id: string) => `/users/${id}/password`,
	},
	CATEGORIES: {
		LIST: "/masters/categories",
		CREATE: "/masters/categories",
		GET_ONE: (id: string) => `/masters/categories/${id}`,
		UPDATE: (id: string) => `/masters/categories/${id}`,
	},
	SUB_CATEGORIES: {
		LIST: "/masters/sub-categories",
		CREATE: "/masters/sub-categories",
		GET_ONE: (id: string) => `/masters/sub-categories/${id}`,
		UPDATE: (id: string) => `/masters/sub-categories/${id}`,
	},
	UNITS: {
		LIST: "/masters/units",
		CREATE: "/masters/units",
		GET_ONE: (id: string) => `/masters/units/${id}`,
		UPDATE: (id: string) => `/masters/units/${id}`,
	},
	GSTS: {
		LIST: "/masters/gsts",
		CREATE: "/masters/gsts",
		GET_ONE: (id: string) => `/masters/gsts/${id}`,
		UPDATE: (id: string) => `/masters/gsts/${id}`,
	},
	SUPPLIERS: {
		LIST: "/masters/suppliers",
		CREATE: "/masters/suppliers",
		GET_ONE: (id: string) => `/masters/suppliers/${id}`,
		UPDATE: (id: string) => `/masters/suppliers/${id}`,
	},
	WAREHOUSES: {
		LIST: "/masters/warehouses",
		CREATE: "/masters/warehouses",
		GET_ONE: (id: string) => `/masters/warehouses/${id}`,
		UPDATE: (id: string) => `/masters/warehouses/${id}`,
		DELETE: (id: string) => `/masters/warehouses/${id}`,
	},
	LABOURS: {
		LIST: "/masters/labours",
		CREATE: "/masters/labours",
		GET_ONE: (id: string) => `/masters/labours/${id}`,
		UPDATE: (id: string) => `/masters/labours/${id}`,
		DELETE: (id: string) => `/masters/labours/${id}`,
	},
	CUSTOMERS: {
		LIST: "/masters/customers",
		CREATE: "/masters/customers",
		GET_ONE: (id: string) => `/masters/customers/${id}`,
		UPDATE: (id: string) => `/masters/customers/${id}`,
		DELETE: (id: string) => `/masters/customers/${id}`,
	},
	HSNCODES: {
		LIST: "/masters/hsn-codes",
		CREATE: "/masters/hsn-codes",
		GET_ONE: (id: string) => `/masters/hsn-codes/${id}`,
		UPDATE: (id: string) => `/masters/hsn-codes/${id}`,
		DELETE: (id: string) => `/masters/hsn-codes/${id}`,
	},
	INVENTORY: {
		LIST: "/inventory",
		CREATE: "/inventory",
		GET_ONE: (id: string) => `/inventory/${id}`,
		UPDATE: (id: string) => `/inventory/${id}`,
		DELETE: (id: string) => `/inventory/${id}`,

		STOCK_OVERVIEW: "/inventory/stock-overview",
		WAREHOUSE_STOCK: "/inventory/warehouse-stock",
		WAREHOUSE_STOCK_ITEM: (itemId: string) =>
			`/inventory/warehouse-stock/${itemId}`,
	},
	REORDER_ITEM_WISE: {
		LIST: "/inventory/reorder-level/item-wise",
		CREATE: "/inventory/reorder-level/item-wise",
		GET_ONE: (id: string) => `/inventory/reorder-level/item-wise/${id}`,
		UPDATE: (id: string) => `/inventory/reorder-level/item-wise/${id}`,
		DELETE: (id: string) => `/inventory/reorder-level/item-wise/${id}`,
	},
	REORDER_WAREHOUSE_WISE: {
		LIST: "/inventory/reorder-level/warehouse-wise",
		CREATE: "/inventory/reorder-level/warehouse-wise",
		GET_ONE: (id: string) => `/inventory/reorder-level/warehouse-wise/${id}`,
		UPDATE: (id: string) => `/inventory/reorder-level/warehouse-wise/${id}`,
		DELETE: (id: string) => `/inventory/reorder-level/warehouse-wise/${id}`,
	},
	WAREHOUSE_INWARD: {
		LIST: "/warehouses/inward",
		CREATE: "/warehouses/inward",
		GET_ONE: (id: string) => `/warehouses/inward/${id}`,
		UPDATE: (id: string) => `/warehouses/inward/${id}`,
		DELETE: (id: string) => `/warehouses/inward/${id}`,
	},
	ENQUIRIES: {
		LIST: "/orders/enquiries",
		LIST_BY_STAGE: (stage: string) =>
			`/orders/enquiries?stage=${encodeURIComponent(stage)}`,
		CREATE: "/orders/enquiries",
		GET_ONE: (id: string) => `/orders/enquiries/${id}`,
		UPDATE: (id: string) => `/orders/enquiries/${id}`,
		UPDATE_STAGE: (id: string) => `/orders/enquiries/${id}/stage`,
		DELETE: (id: string) => `/orders/enquiries/${id}`,
	},
	QUOTATIONS: {
		LIST: "/orders/quotations",
		REQUESTS: "/orders/quotations/requests",
		CREATE: "/orders/quotations",
		GET_ONE: (id: string) => `/orders/quotations/${id}`,
		UPDATE: (id: string) => `/orders/quotations/${id}`,
		UPDATE_STATUS: (id: string) => `/orders/quotations/${id}/status`,
		DELETE: (id: string) => `/orders/quotations/${id}`,
	},
	WAREHOUSE_OVERVIEW: {
		DAILY_LOG: (warehouseName: string) =>
			`/warehouses/warehouse-overview/daily-log?warehouseName=${encodeURIComponent(warehouseName)}`,
		IN_STOCK: (warehouseName: string) =>
			`/warehouses/warehouse-overview/in-stock?warehouseName=${encodeURIComponent(warehouseName)}`,
	},

	STOCK_TRANSFER: {
		LIST: "/warehouses/stock-transfer",
		PENDING: "/warehouses/stock-transfer/pending",
		CREATE: "/warehouses/stock-transfer",
		GET_ONE: (id: string) => `/warehouses/stock-transfer/${id}`,
		UPDATE: (id: string) => `/warehouses/stock-transfer/${id}`,
		REVERT: (id: string) => `/warehouses/stock-transfer/${id}/revert`,
		COMPLETE: (id: string) => `/warehouses/stock-transfer/${id}/complete`,
	},
	ISSUE_TO_LABOUR: {
		LIST: "/warehouses/issue-to-labour",
		GET_ONE: (id: string) => `/warehouses/issue-to-labour/${id}`,
		CREATE: "/warehouses/issue-to-labour",
		UPDATE: (id: string) => `/warehouses/issue-to-labour/${id}`,
		REVERT: (id: string) => `/warehouses/issue-to-labour/${id}/revert`,
		COMPLETE: (id: string) => `/warehouses/issue-to-labour/${id}/complete`,
		PENDING: "/warehouses/issue-to-labour/pending",
	},
	DASHBOARD: "/dashboard",
	DASHBOARD_INVENTORY_TABLE: "/dashboard/inventory-table",
};
